version: '3.8'

services:
  # Blockchain Node (Hardhat)
  blockchain-node:
    build:
      context: ./blockchain
    ports:
      - "8545:8545" # RPC port
    volumes:
      - ./blockchain/contracts_meta:/app/contracts_meta # Share ABI & address
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8545"]
      interval: 10s
      timeout: 5s
      retries: 5

  # IPFS Node (Kubo)
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "4001:4001" # p2p
      - "5001:5001" # API
      - "8080:8080" # Gateway
    volumes:
      - ./ipfs_data:/data/ipfs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend (Flask)
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./blockchain/contracts_meta:/app/contracts_meta:ro # Read-only access to ABI
    env_file:
      - ./backend/.env
    depends_on:
      blockchain-node:
        condition: service_healthy
      ipfs:
        condition: service_healthy
    networks:
      - app-network

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge