version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
    # This is the corrected command
    command: python3 -m flask run --host=0.0.0.0 --reload
  
  frontend:
    build:
      context: ./frontend
      target: build
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev